version: '3.8'

services:
  db:
    image: postgres:15 
    container_name: api-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=apidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: api-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=apidb;Username=admin;Password=supersecret
      - ASPNETCORE_URLS=http://+:8080 
    depends_on:
      - db

volumes:
  postgres_data:
